name = "readtalk-pages"
type = "typescript"
compatibility_date = "2026-01-24"
account_id = "53d61c09062b1ca11788fa763f79313a"

[build]
command = "npm run build"
upload.format = "service-worker"
upload.dir = "dist"                

[[bindings]]
type = "service_worker"
name = "OPENAUTH_WORKER"           
service = "openauth"               
environment = "production"

[[bindings]]
type = "service_worker"
name = "READTALK_WORKER"           
service = "account"               
environment = "production"
